import Head from "next/head";
import { motion as m } from "framer-motion";
import React, { useEffect } from "react";
import Navbar from "@/components/navBar";
import ContactForm from "@/components/contactForm";

export default function contact({}) {
  return (
    <m.div
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      exit={{ opacity: 1 }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      className=" bg-whitey absolute top-0 left-0 bottom-0 right-0  min-w-screen min-h-screen "
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <m.h1
        animate={{ y: 0 }}
        initial={{ y: "60%" }}
        transition={{ delay: 0.5, duration: 0.5 }}
      >
        <div className="md:text-9xl md:ml-10 ml-5 text-6xl mt-20 font-myTupiBold ">
          CONTACT{" "}
        </div>
        <div className="border-b border-black "></div>
        <ContactForm />
      </m.h1>{" "}
    </m.div>
  );
}
